tweag/rules_sh

.buildkite/pipeline.yml, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/settings.yml, .mergify.yml, AUTHORS, CONTRIBUTING.md, CONTRIBUTORS, LICENSE
Adds the following files taken from [`rules_haskell`](https://github.com/tweag/rules_haskell) and adapted for this repository.
- `AUTHORS`: lists copyright holders
- `CONTRIBUTORS`: lists people who have a agreed to CLA
- `CONTRIBUTING.md`: contributer guidelines
- `LICENSE`: Apache license
- `.github`: GitHub labels, codeowners, and repository config
- `.buildkite`: BuildKite CI configuration
- `.mergify`: Mergify configuration
=> Add standard files

sh/posix.bzl
Autodetection using `repository_ctx.which` is not safe on Windows, as it may turn up false friends. E.g. Windows has a `find.exe` which is unrelated to POSIX `find`. Instead we follow the example of [`@bazel_tools//tools/sh:sh_configure.bzl`](https://github.com/bazelbuild/bazel/blob/223ef9d28bc8ec03ead471c74c32cd86f0baf835/tools/sh/sh_configure.bzl#L29-L44) and use tools next to `bash.exe`.
This repository currently doesn't have Windows CI. However, [`rules_haskell`'s CI passes](https://dev.azure.com/tweag/rules_haskell/_build/results?buildId=3360&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3) with [these changes](https://github.com/tweag/rules_haskell/commit/6221c3e4be7e37f1a24b7128c2b48f72140be7ad).
=> Safer sh_posix_configure on Windows

sh/posix.bzl, sh/repositories.bzl
See https://github.com/tweag/rules_haskell/pull/1196
- Uses `@platforms//<setting>:<value>` instead of `@bazel_tools//platforms:<value>`.
- Loads `@platforms` in `rules_sh_dependencies`.
=> Use platforms repo for constraints

.buildkite/image/Dockerfile, .buildkite/pipeline.yml
The buildkite workers are now running on NixOS. However, `rules_sh` should be tested outside a Nix environment (`rules_nixpkgs` provides the relevant Nix extensions). We follow `rules_haskell`'s example and run the pipeline in a dedicated Docker container.
=> Run CI in Docker container

sh/BUILD.bazel, sh/posix.bzl
`bzl_library` target definitions [are required to generate Stardoc documentation](https://github.com/bazelbuild/stardoc/blob/master/docs/skydoc_deprecation.md#starlark-dependencies) for any rules set that depends on `rules_sh`. This change is motivated by https://github.com/tweag/rules_haskell/pull/1244.
=> Define bzl_library for rules_sh

CHANGELOG.md, sh/posix.bzl
This PR fixes #13 
* `bazel test //...`
* `bazel test //...` in [rules_nixpkgs](https://github.com/tweag/rules_nixpkgs) with the appropriate patch: https://github.com/tweag/rules_nixpkgs/pull/117
* `bazel test //...` test in [rules_haskell](https://github.com/tweag/rules_haskell) by using `rules_nixpkgs` from the previous bullet
=> sh_posix_toolchain: reduce number of attributes by using attr.string_dict instead of attr.string list

CHANGELOG.md, MAINTAINERS.md
- Prepare `CHANGELOG.md`
- Add `MAINTAINERS.md` to version the release procedure, mostly copying @aherrmann's procedure in comment https://github.com/tweag/rules_sh/pull/14#pullrequestreview-381935009
The need for a release was motivated here: https://github.com/tweag/rules_sh/pull/14#issuecomment-604362296
=> Release 0.2.0

.bazelci/presubmit.yml, .github/workflows/workflow.yaml, MAINTAINERS.md, MODULE.bazel, bzlmod/extensions.bzl, sh/posix.bzl
For compatibility with bzlmod and addition to the https://github.com/bazelbuild/bazel-central-registry.
This version has been added to the BCR in https://github.com/bazelbuild/bazel-central-registry/pull/38 already. The changes introduced by this PR are so that future versions will no longer [require patching](https://github.com/bazelbuild/bazel-central-registry/pull/38/files#diff-6067dfb1d9cd3806078e211bf7f4d97ce8e8722f3af151b3af162ac63217e303R5) to be added to the BCR.
Adds a module rule `sh_configure` for the POSIX toolchain configured by `sh_posix_configure`. Module rules may invoke repository rules, but may not register toolchains. This commit adds a boolean parameter `register` to `sh_posix_configure` for compatibility with both the old repository rule workflow and the new module …
=> "Modularize" rules_sh

sh/posix.bzl
=> Recognize `arm64` CPU value correctly for OSX and Windows

.github/workflows/workflow.yaml
The problem reported in https://github.com/bazelbuild/bazel-central-registry/pull/47#issuecomment-998883652 should be fixed.
=> Cleanup: Use Bazel version 5.1.0 to test bzlmod

sh/private/BUILD.bazel, sh/private/defs.bzl, sh/sh.bzl, tests/sh_binaries/sh_binaries_test.bzl
The implementation introduced in #23 is a little too eager and will also split the extension in cases like `ld.gold`.
=> sh_binaries: Only strip .exe and similar extensions on Windows

WORKSPACE, sh/import.bzl, sh/repositories.bzl, tests/import/BUILD.bazel, tests/import/create_shim_test.sh, tests/import/import_test.bzl, tests/import/invoke_shim_test.sh
Part of https://github.com/tweag/rules_sh/issues/19
The `sh_binaries` rule can bundle Bazel tracked executable `File`
objects as collections of tools. Tools can be imported into Bazel by
download or built by Bazel. However, in some use-cases, users need to
import executales that are installed outside of Bazel from the system.
On Unix systems this can be achieved in a hermetic way by creating a
symbolic link in a repository rule. However, on Windows, symbolic file
links are not generally available and the corresponding `repository_ctx`
method will create a copy. However, file copies do not generally work,
as executables may expect auxiliary files next to their installation
path.
A shim offers an alternative on Windows. A shim is a small executable,
accompanied by a small data file that …
=> Implement create_shim to create a shim on Windows

.github/workflows/workflow.yaml, BUILD.bazel, MODULE.bazel, README.md, WORKSPACE, sh/BUILD.bazel, sh/docs/BUILD.bazel, sh/docs/func.vm, sh/docs/header.vm, sh/posix.bzl, sh/private/BUILD.bazel, sh/repositories.bzl
This change adds targets for automatically generating `README.md` from stardoc docstrings as requested in #24.
* Verify that `README.md` is up-to-date: `bazel test //sh/docs:check-readme` 
* Update `README.md` if necessary: `bazel run //sh/docs:update-readme`
Due to a [stardoc / bzlmod issue](https://github.com/bazelbuild/stardoc/issues/117) these targets are not run for "modules" pipelines on CI. They are also disabled for Windows because it [fails to parse](https://github.com/tweag/rules_sh/runs/7994246856?check_suite_focus=true) the docstring for some reason (I'm guessing line ending differences):
```
sh\repositories.bzl:4:5 line 22: closing docstring quote should be indented the same as the opening quote
```
=> Use stardoc to automatically generate README.md

.bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json
Take the [template files from the Publish to BCR project](https://github.com/bazel-contrib/publish-to-bcr/tree/main/templates), customize them, and add them to the root of project.
The `presubmit.yaml` is based on what we were already using in the BCR.
After this, creating a new release of `rules_sh`, should result in an automated commit to [our fork of the BCR](https://github.com/tweag/bazel-central-registry) and a PR from there to the BCR.
Resolves #36
=> Add Publish to BCR templates

.bcr/presubmit.yml, MODULE.bazel, bzlmod/extensions.bzl
Version 0.3.0 currently requires a [patch](https://github.com/bazelbuild/bazel-central-registry/blob/main/modules/rules_sh/0.3.0/patches/fix-version.patch) in the central registry. This PR should make this patch obsolete.
* update version in `MODULE.bazel` to match the current release
* use `register_toolchain` instead of `module.toolchains_to_register`
* add `rules_sh_shim_exe` repository in the bzlmod extension
* use `local_posix_config` and `rules_sh_shim_exe` repositories
* update `presubmit.yml` file to match the one in the BCR
See https://github.com/bazelbuild/bazel-central-registry/pull/151
=> Bring module up to par with BCR

.bcr/metadata.template.json, .github/CODEOWNERS
Assign the designated project steward as CODEOWNERS.
=> Set CODEOWNERS

.github/workflows/workflow.yaml
Currently, the CI workflow is triggered when pushing to this repository.
We should also trigger the workflow for PRs contributed from somebody else.
=> Run CI workflow for PRs too

MODULE.bazel, bzlmod/extensions.bzl
I have a use case where I want to register my own posix toolchain and don't want Bazel to fall back to using the `local_posix` toolchain (the toolchain I'm making has certain constraints — when they aren't met I want Bazel to error).
`sh_posix_configure` provides an easy way to skip registering the local toolchain at `@local_posix_config//:local_posix_toolchain` but using `rules_sh` via bzlmod does not expose a way to configure this:
https://github.com/tweag/rules_sh/blob/0e3d91d962ebbbc2425a6414d0052ff43d853149/MODULE.bazel#L14
While we can condition the `register_toolchains` invocation [^1] in `MODULE.bazel` (i.e. `register_toolchains(...) if <condition> else None` is permitted), unfortunately, as far as I know, there isn't a way to read data from module extension tag classes within …
=> Allow disabling the toolchain `sh_configure` creates under bzlmod

MODULE.bazel
This reduces the number of transitive deps that are pulled into modules that depend on `rules_sh`.
I couldn't find it in the changelog but as far as I can tell the `dev_dependency` option on `bazel_dep` [was added in 5.0](https://github.com/bazelbuild/bazel/commit/e83858bca9112e70f60b56fa70dcc01d42e4fa03) so I don't think this is a breaking change.
---
I haven't added [`--ignore_dev_dependency`](https://bazel.build/reference/command-line-reference#flag--ignore_dev_dependency) to CI to ensure that the tests pass without the `stardoc` dep but I can update this PR to do so if that's appropriate.
=> Mark `stardoc` as a dev dependency

.bazelrc, CONTRIBUTING.md
Other repositories were already using the config name `remote-cache`.  Given that Bazel has many caches, this is a better name.
Related to https://github.com/tweag/scalable-builds-group/issues/107.
=> chore: rename cache config group to remote-cache

.github/actions/run_bazel_test/action.yaml, .github/actions/run_bazel_test/run_bazel_test.sh, .github/workflows/workflow.yaml
Create a GitHub action to execute `bazel test //...`. It supports running in a specific working directory. It also supports executing on Windows, Linux and MacOS.
=> chore: refactor bazel test execution to a GitHub action

CHANGELOG.md, MODULE.bazel, tests/MODULE.bazel
A new release is in order since version 0.3.0 that is currently published to the BCR is not compatible with Bazel 7, as it is failing on amd64 Darwin with:
```
(07:18:17) INFO: ToolchainResolution: Performing resolution of @@rules_sh~0.3.0//sh/posix:toolchain_type for target platform @@local_config_platform//:host
ToolchainResolution:   Toolchain @@rules_sh~0.3.0~sh_configure~local_posix_config//:local_posix is compatible with target plaform, searching for execution platforms:
ToolchainResolution:     Incompatible execution platform @@local_config_platform//:host; mismatching values: linux
ToolchainResolution: No @@rules_sh~0.3.0//sh/posix:toolchain_type toolchain found for target platform @@local_config_platform//:host.
(07:18:17) INFO: ToolchainResolution: Performing resolution of …
```
=> Prepare release 0.4.0

.bcr/presubmit.yml
This PR syncs back the `presubmit.yml` file from https://github.com/bazelbuild/bazel-central-registry/pull/1228 so for the next release the Publish to BCR PR is readily prepared.
=> Sync presubmit.yml file from BCR

.github/workflows/workflow.yaml
bazelisk is provided by Github's runner image by default, and the action is deprecated and has been
superseded by [setup-bazel].
[setup-bazel]: https://github.com/bazel-contrib/setup-bazel
closes #77, closes #80
=> CI: Remove bazelbuild/setup-bazelisk step

.github/renovate.json
Repository problems
These problems occurred while renovating this repository.
Found renovate config warnings
```
The "platform" option is a global option reserved only for Renovate's global configuration and cannot be configured within a repository's config file.
```
=> Fix renovate configuration error
